# Generated by Django 6.0.2 on 2026-02-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='jiraID',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
