# Generated by Django 6.0.2 on 2026-03-29 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='isDeleted',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='jiraID',
            new_name='jira_id',
        ),
    ]
