# Generated by Django 6.0.2 on 2026-02-25 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='jira_access_token',
            field=models.CharField(default=None, max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
