# Generated by Django 6.0.2 on 2026-03-17 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.IntegerField(choices=[(0, 'Developer'), (1, 'Admin')], default=0),
        ),
    ]
