# Generated by Django 6.0.2 on 2026-03-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_projectmember_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='isDeleted',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='projectmember',
            old_name='isDeleted',
            new_name='is_deleted',
        ),
        migrations.AlterField(
            model_name='project',
            name='jira_project_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='key',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Archived'), (2, 'Active')], default=2),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Developer'), (2, 'Admin')], default=1),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Invited'), (2, 'Active'), (3, 'Revoked'), (4, 'Rejected')], default=1),
        ),
    ]
