# Generated by Django 6.0.2 on 2026-02-20 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='verification_token',
        ),
    ]
