# Generated by Django 6.0.2 on 2026-03-29 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_emailverification_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverification',
            old_name='isDeleted',
            new_name='is_deleted',
        ),
    ]
