# Generated by Django 6.0.2 on 2026-02-20 20:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_emailverification_verification_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='verification_token',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
