# Generated by Django 6.0.2 on 2026-03-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='jira_id',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
