# Generated by Django 6.0.2 on 2026-03-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comment_jira_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='isDeleted',
            new_name='is_deleted',
        ),
        migrations.AlterField(
            model_name='comment',
            name='jira_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
