# Generated by Django 6.0.2 on 2026-03-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='severity',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Mid'), (3, 'High')], default=1),
        ),
    ]
