# Generated by Django 6.0.2 on 2026-03-18 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_ticket_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='jira_id',
            new_name='jira_key',
        ),
    ]
