# Generated by Django 6.0.2 on 2026-03-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_rename_jira_id_ticket_jira_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='jira_key',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=100),
            preserve_default=False,
        ),
    ]
