# Generated by Django 6.0.2 on 2026-03-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_alter_ticket_jira_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='isDeleted',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='ticketsubscriber',
            old_name='isDeleted',
            new_name='is_deleted',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='jira_key',
            field=models.CharField(blank=True, db_index=True, max_length=100, unique=True),
        ),
    ]
